export enum ActionType {    
    GET_GIFS_FROM_API='GET_GIFS_FROM_API',
    UPDATE_GIFS_TO_STORE='UPDATE_GIFs_TO_STORE',
    SEARCH_GIFS_FROM_API='SEARCH_GIFS_FROM_API',
    LOADMORE_GIFS_FROM_API='LOADMORE_GIFS_FROM_API',
    APPEND_GIFS_TO_STORE='APPEND_GIFS_TO_STORE',
    SET_MODAL_CONTENT='SET_MODAL_CONTENT',
    SET_MODAL_STATE='SET_MODAL_STATE',
    SET_API_ERROR='SET_API_ERROR'
}